
language: node_js
node_js:
- 'stable'
- '5.0.0'
- '4.0.0'
install:
- npm install
services: mongodb
env:
  global:
    - export TWILIO_ACCOUNT_SID=AC2XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    - export TWILIO_AUTH_TOKEN=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    - export TWILIO_NUMBER=+15551230987
    - export MONGO_URL_TEST=mongodb://localhost/appointment-reminders-node-test
